### ISSUE TITLE
Encoding in Connection

### ISSUE THREAD

**Issue by 1995parham** [elahe-dastan/NATS#5]
NATS allows you to use encoding on connections. When you use this feature, you must use it on both sides, so you need to use encoding in the subscription phase or remove it from the producer side.

**Comment by elahe-dastan** [comment]
Now I have the same encoding on both sides, but still have the problem :(

**Comment by 1995parham** [comment]
Please note that when you are creating an encoded connection, you need to use that for your publish and subscribe. You by mistake use the old connection (the pure nats not the encoded one) for subscribing and this cause an issue :scream:

**Comment by 1995parham** [comment]
Besides that when you are using the encoded connection you must use your model for seeing and receiving messages.
